

export const Negocios = [
    {
        nombre:'Importadora Corsa Motors',
        celular:573138562763,
        direccion: 'cra27a #64a-59',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet'],
        carros:[],
        descripcion:'',
        servicios:['Frenos', 'Suspension', 'Motor', 'Electricos', 'Inyeccion',],
        premium:true,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        id:1,
    },
    {
        nombre:'Universal Repuestos',
        celular:573134344344,
        direccion: 'Calle 65 #26-48',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:2

    },
    {
        nombre:'Marcar',
        celular:573134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        carros:[],
        servicios:['Cambio de Aceite', 'Cambio de Arrastre'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:3

    },
    {
        nombre:'Marcar',
        celular:573134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        carros:[],
        servicios:['Cambio de Aceite', 'Cambio de Arrastre'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:4

    },
    {
        nombre:'AutoPartes Marcar',
        celular:573134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        carros:[],
        servicios:['Cambio de Aceite', 'Cambio de Arrastre'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:40

    },
    {
        nombre:'Impocolrep',
        celular:573134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:41


    },
    {
        nombre:'Auto Brasil',
        celular:573134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:42


    },
    {
        nombre:'Importadora Celeste',
        celular:573134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:5
    },
    {
        nombre:'Importadora Boada',
        celular:573045919550,
        direccion: 'calle 65 #26-64',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Renault','Chevrolet', ],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:6
    },
    {
        nombre:'Universal de Repuestos',
        celular:573134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:7
    }
    ,
    {
        nombre:'Importadora ChevroMotor',
        celular:null,
        direccion: 'Cll 65 #26-49',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Ford', 'Renault','Hyundai'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:8
    }
    ,
    {
        nombre:'Rodamientos y Correas la 65',
        celular:null,
        direccion: 'Cra 26 #64-33',
        imagen:'',
        tipo:'Almacen',
        marcas:['Rodamientos', 'Correas'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:9
    }
    ,
    {
        nombre:'Camperos DODO Japones',
        celular:573125741044,
        direccion: 'Cra 26 #66-88',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Mitsubishi','Hyundai'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:10
    }
    ,
    {
        nombre:'Campero Motors Cm',
        celular:573007881509,
        direccion: 'Cra 26 #66-84',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Mitsubishi','Hyundai'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:11
    }
    ,
    {
        nombre:'Nissan Japon Motors ',
        celular:573138426352,
        direccion: 'Cra 26 #66-80',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Hyundai'],
        descripcion:'',
        servicios:[],
        carros:['Sentra', 'Almera', 'Tiida', 'Frontier', 'Xtrail'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:12
    }
    ,
    {
        nombre:'El AutoMovil Japones',
        celular:null,
        direccion: 'Cra 26 #66-76',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Mitsubishi'],
        descripcion:'',
        servicios:[],
        carros:['Corolla', 'Celica', 'Hilux', 'Sentra', 'Urban', 'd21', 'd22'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:13
    },
    {
        nombre:'Nissan Toyota Motors',
        celular:573105848390,
        direccion: 'Cra 26 #66-46',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:14
    },
    {
        nombre:'El punto Nissan',
        celular:null,
        direccion: 'Cra 26 #66-42',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Mitsubishi'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:15
    },
    {
        nombre:'Tokyo Camperos',
        celular:573194883672,
        direccion: 'Cra 26 #66-20',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Mitsubishi'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:16
    },
    {
        nombre:'Importadora Cherokke y Toyota',
        celular:573124484581,
        direccion: 'Cra 26 #66-18',
        imagen:'',
        tipo:'Almacen',
        marcas:['Dodge', 'Jeep', 'Chrysler','Toyota'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:17
    },
    {
        nombre:'Jeep Camperos',
        celular:null,
        direccion: 'Cra 26 #66-09',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Mitsubishi'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:18
    },
    {
        nombre:'Todo Camperos Japoneses',
        celular:null,
        direccion: 'Cra 26 #66-19',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Mitsubishi'],
        descripcion:'',
        carros:[],
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:19
    },
    {
        nombre:'Chevro Japon',
        celular:null,
        direccion: 'Cra 26 #66-27',
        imagen:'',
        tipo:'Almacen',
        marcas:['Chevrolet'],
        descripcion:'',
        servicios:[],
        carros:['Blazer', 'Swift', 'Vitara', 'Cavalier', 'Luv', 'Corsa', 'Cheyenne', 'Samurai', 'SuperCarry', 'Sprint', 'Tropper', 'NKR'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:20
    },
    {
        nombre:'Brake Pak',
        celular:573138533587,
        direccion: 'Cra 26 #66-45',
        imagen:'',
        tipo:'Almacen',
        marcas:[],
        descripcion:'',
        servicios:['Frenos'],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:21
    },
    {
        nombre:'MultiCamperos',
        celular:573043533363,
        direccion: 'Cra 26 #66-73',
        imagen:'',
        tipo:'Almacen',
        marcas:['Toyota', 'Mitsubishi', 'Nissan'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:22
    },
    {
        nombre:'La Chevrolet y Camperos',
        celular:573194883672,
        direccion: 'Cra 26 #65-81',
        imagen:'',
        tipo:'Almacen',
        marcas:['Chevrolet', 'Ford', 'Mazda', 'Kia', 'Toyota'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:23
    },
    
    {
        nombre:'Carli Repuestos',
        celular:573115454960,
        direccion: 'Cra 26 #65-90',
        imagen:'',
        tipo:'Almacen',
        marcas:['Chevrolet', 'Renault', 'Mazda'],
        descripcion:'',
        servicios:[],
        carros:['Megane', 'Duster', 'Clio', 'Twingo', 'Symbol', 'Mazda3', 'Optra', 'Sonic', 'Tracker', 'Sprint', 'Tropper', 'Dmax'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:24
    },
    {
        nombre:'Autopartes Aregom',
        celular:573133392300,
        direccion: 'Cra 26 #65-90',
        imagen:'',
        tipo:'Almacen',
        marcas:['Chevrolet', 'Renault', 'Mazda'],
        descripcion:'',
        servicios:[],
        carros:['Megane', 'Duster', 'Clio', 'Twingo', 'Symbol', 'Mazda3', 'Optra', 'Sonic', 'Tracker', 'Sprint', 'Tropper', 'Dmax', 'Sail'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:25
    },
    {
        nombre:'A.E Repuestos',
        celular:573108146760,
        direccion: 'Cra 26 #65-80',
        imagen:'',
        tipo:'Almacen',
        marcas:['Nissan', 'Toyota', 'Citroen','Volkswagen', 'Peugeot'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:26
    },
    {
        nombre:'Sincropartes',
        celular:573107177510,
        direccion: 'Cra 26 #65-74',
        imagen:'',
        tipo:'Almacen',
        marcas:[],
        descripcion:'',
        servicios:['Sincronizacion', 'Bujias', 'Bobinas', 'Sensores', 'Filtros'],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:27
    },
    {
        nombre:'Importadora Korea Japon',
        celular:573174031533,
        direccion: 'Cra 26 #65-72',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Kia',  'Toyota', 'Nissan'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:28
    },
    {
        nombre:'Rotulas y Partes',
        celular:573204284737,
        direccion: 'Cra 26 #65-70',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Kia', 'Renault', 'Nissan'],
        descripcion:'',
        servicios:['Suspension', 'Rotulas', 'Terminales'],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:29
    },
    {
        nombre:'Autopartes Ercar',
        celular:null,
        direccion: 'Cra 26 #65-52',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet', 'Kia', 'Ford', 'Nissan'],
        descripcion:'',
        servicios:[],
        carros:['Megane', 'Duster', 'Clio', 'Twingo', 'Symbol', 'Mazda3', 'Optra', 'Sonic', 'Tracker', 'Sprint', 'Tropper', 'Dmax', 'Sail'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:30
    },
    {
        nombre:'Todo Motor',
        celular:null,
        direccion: 'Cra 26 #65-50',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet','Renault',],
        descripcion:'',
        servicios:[],
        carros:['Megane', 'Duster', 'Clio', 'Twingo', 'Symbol', 'Mazda3', 'Optra', 'Sonic', 'Tracker', 'Sprint', 'Tropper', 'Dmax', 'Sail'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:31
    },
    {
        nombre:'Auto Brasil',
        celular:null,
        direccion: 'Cra 26 #65-73',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet','Renault'],
        descripcion:'',
        servicios:[],
        carros:['323', 'b2000', 'b2200', 'Twingo', 'Symbol', 'Mazda3', 'Optra', 'Sonic', 'Tracker', 'Sprint', 'Tropper', 'Dmax', 'Sail'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:32
    },
    {
        nombre:'Rimar',
        celular:null,
        direccion: 'Cra 26 #65-59',
        imagen:'',
        tipo:'Almacen',
        marcas:['Jeep', 'Ford','Chevrolet', 'Dodge'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:33
    },
    {
        nombre:'Ercar Diesel',
        celular:null,
        direccion: 'Cra 26 #65-47',
        imagen:'',
        tipo:'Almacen',
        marcas:[ 'Ford','Chevrolet', 'Nissan', 'Mazda'],
        descripcion:'',
        servicios:[],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:34
    },
    {
        nombre:'El mundo del Amortiguador',
        celular:null,
        direccion: 'Cra 26 #65-43',
        imagen:'',
        tipo:'Almacen',
        marcas:[],
        descripcion:'',
        servicios:['Amortiguadores'],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:35
    },
    {
        nombre:'Big Radiators',
        celular:null,
        direccion: 'Cra 26 #65-25',
        imagen:'',
        tipo:'Almacen',
        marcas:[],
        descripcion:'',
        servicios:['Radiadores'],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:36
    },
    {
        nombre:'Renault 19',
        celular:null,
        direccion: 'Cra 26 #65-19',
        imagen:'',
        tipo:'Almacen',
        marcas:['Renault'],
        descripcion:'',
        servicios:[],
        carros:['Megane', 'Logan', 'Symbol', 'Clio', 'Twingo', 'Laguna'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:37
    },
    {
        nombre:'FerAutos',
        celular:null,
        direccion: 'Cra 26 #65-15',
        imagen:'',
        tipo:'Almacen',
        marcas:['Ford'],
        descripcion:'',
        servicios:[],
        carros:['Explorer', 'Ranger', 'Escape', 'Fusion', 'Fiesta', 'Edge', 'Ecosport'],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:38
    },
    {
        nombre:'Frenos Lepair',
        celular:573115417819,
        direccion: 'Cra 26 #65-18',
        imagen:'',
        tipo:'Almacen',
        marcas:['Ford'],
        descripcion:'',
        servicios:['Guayas', 'Frenos'],
        carros:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
        fecha:'3-10-2022',
        id:39
    },
]