

export const Negocios = [
    {
        nombre:'Corsa Motors',
        celular:3138562763,
        direccion: 'cra27a #64a-59',
        imagen:'',
        tipo:'Almacen',
        marcas:['Mazda', 'Chevrolet'],
        descripcion:'',
        servicios:[],
        premium:false,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
    },
    {
        nombre:'Marcar',
        celular:3134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Taller',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        premium:true,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
    },
    {
        nombre:'Impocolrep',
        celular:3134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Taller',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        premium:true,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
    },
    {
        nombre:'Auto Brasil',
        celular:3134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Taller',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        premium:true,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
    },
    {
        nombre:'Importadora Celeste',
        celular:3134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Taller',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        premium:true,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
    },
    {
        nombre:'Boada',
        celular:3134344344,
        direccion: 'cra21a #69a-45',
        imagen:'',
        tipo:'Taller',
        marcas:['Mazda', 'Chevrolet', 'Ford'],
        descripcion:'',
        servicios:[],
        premium:true,
        ciudad:'Bogota',
        pais:'Colombia',
        precio:'',
    }
]